### ISSUE TITLE
simple question 

### ISSUE THREAD

**Issue by dutchsing009** [jlian2/Improved-Voice-Conversion-with-Conditional-DSVAE#1]
Really great paper here !! I read it all ,, Will the code be released for the improved version too aka this repo DSVAE ?? or only the style transfer one ?

Thanks in advance

**Comment by jlian2** [comment]
Hi! Thanks for your interest. We expect to release the code later on. But I think the model is well described in the paper and it should not be difficult to reproduce. If you have any other questions, please let me know.

**Comment by dutchsing009** [comment]
Hi! Thank for your very fast reply. First Congratulations 10 hours ago I saw that your paper got accepted at Interspeech 2022 and got v2 revision :) . Second yes the model is described well but I think I will wait till the official implementation. Third I know that in the demo everything is unseen to unseen but the seen to seen is very very interesting.
![Annotation 2022-06-22 161038](https://user-images.githubusercontent.com/103085811/175050728-02d8ce4e-072d-42d0-8b96-2e91e9fc3f10.png)
will we have the ability to train seen to seen in the repo ? also will we be able to do the DSVAE(WavLM) or only the DSVAE(hifigan) ? like would we be able to choose which method we can use , as DSVAE(WavLM) has the best results of all especially the seen to seen (WavLM). last thing for me here do you think this method can work on singing voices ?? like can it do (SVC) that would be really nice to know. If you don't mind I have these 3 English singers samples from NUS-48E you can try to convert between them , i put them in (source,target) way , it would be eye opening to see the results since you might have the code, here it is https://drive.google.com/file/d/1rMczavRJNeKinYIOr5f4zaydvNlPMc9-/view?usp=sharing
Thanks in advance : )

**Comment by jlian2** [comment]
Hi! Thanks for your interests. We also want to release the code ASAP, however, the copyright belongs to the company and the open source has to follow the standard process and we cannot tell the specific date. In the meanwhile, we have concurrent works that are based on this repo. You can also check our most recent UTTS work which takes VC as a subset. https://arxiv.org/abs/2206.02512. I would suggest you try to implement your codebase or your can also refer the unofficial DSVAE implementation https://arxiv.org/abs/1803.02991 because they are similar. All details are well included in the paper. If you want to make your own implementation and encounter some problems, you can just let me know. We did not test them for singing voices. For the remaining parts, I will try to discuss with my collaborators on this. Thanks!

**Comment by ebagjones** [comment]
Outstanding work, also very interested in whenever this is released. I appreciate with how long it can take to have corporate lawyers approve something like code release... but if you were to guess, would you estimate weeks or months?
Also, I fully agree w/ @dutchsing009  that seen to seen is definitely interesting!
Again - outstanding work.

**Comment by jlian2** [comment]
Hi! To reply in general, we would encourage you to implement the code by yourself if you plan to immediately run it. We can not say too much about that due to copyright issue. But probably we will not release it until next year.
