### ISSUE TITLE
Clarification: Encoder Implementation Details

### ISSUE THREAD

**Issue by apoorvagnihotri** [jlian2/Improved-Voice-Conversion-with-Conditional-DSVAE#7]
Hi @jlian2. 

- while understanding the implementation, I don't understand what is meant by pooling. 
- Is it [torch.nn.AvgPool2d](https://pytorch.org/docs/stable/generated/torch.nn.AvgPool2d.html#avgpool2d)? If so, what are the hyperparameters used?

![image](https://user-images.githubusercontent.com/22618985/198025958-aac287be-215b-4f54-afa1-fc96c06705cd.png)

- Additionally, in the shared encoder, how is InstanceNorm2d used? Reading the documentation on pytorch's website (image below), it mentions to be useful for 4D data. But as I understand the batches in the VAE model would be 3 dimensional. (batch_size, channels, sequence_length)

![image](https://user-images.githubusercontent.com/22618985/198065174-2b739246-a0ed-4a53-b258-77a588364386.png)

**Comment by jlian2** [comment]
Pooling means average over time
For INS2D, you need to unsqueeze the data to 4D.

**Comment by XernPLL** [comment]
I think i dont understand something...
So on the beggining we have mel (batch, frames, frequency) next we modify that to have something like (batch*frames, 1, frequency)?
And after that we use Conv1D to generate more channels (batch*frames, channels[256], frequency[smaller because kernel])
And after that we use instancenorm on (batch, channels[256], frames, frequency)
And after all of that we just FC that frequency and channels to have sth like (batch,frames,embed space)?

I'd be grateful for an explanation
